---
- name: sample playbook
  hosts: server
  remote_user: vaishnavi16d107
  become: true
  tasks:
    - name: installing httpd
      yum: 
            name: httpd
            state: installed
    - name: starting httpd
      service:
             name: httpd
             state: started
     
   
